
package com.outerspace.kurbandictionary.api;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

/**
 * TermDefinitionList.
 * The list of all definitions corresponding to a term.
 *
 * This class is the Java equivalent to the JSON response received from the server.
 * The class was generated by the http://jsonschema2pojo.org JSON converter with all
 * the annotations for GSON. It was left as a java class to ease possible maintenance
 *
 */

public class TermDefinitionList {

    @SerializedName("list")
    @Expose
    public java.util.List<TermDefinition> list = new ArrayList<TermDefinition>();

}
